spring.application.name=booking-service

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.admin.email=admin@barbook.com
app.admin.password=Admin@123
app.admin.full-name=System Admin

app.jwt.secret=mlMPluBWtwx5Vjdko0jO5l2IGt2pAUpzSt0KxpixumWcfE8f/KZ/c2k/KzCX3gHPga7EhfLh9sBQDXMXKL8+Gw==
app.jwt.expiration-ms=86400000